### PR TITLE
Improve energy calculation

### PR DESCRIPTION
**Pull request by darvader**
I figured out that the calculated energy consumption is still too high because Kostal is updating only every 5 mins. So I calculated the delta in between. Now the consumption seems really close to my observations and measurements.

### CODE REVIEW

**Comment by davwil** [comment]
Thank's for creating this PR and also adding the logging config. I'll sadly need a little bit more time to look into it and primarily test it - sorry for the delay!

**Comment by leiweke** [comment]
I can confirm that the code from darvader is working since month, running on my system and it improves the numbers. Many Thanks for the improvements.

**Comment by ankaoha** [comment]
Thanks to both of you. With the new changes, recording the values ​​in the VRM portal works perfectly. Good work!

**Comment by davwil** [comment]
Thank's for the contribution! I've integrated the energy calculation into the main.

Regarding the logging config: we would need to make sure that we rotate and remove old log files, otherwise the disk may run full. Thus i've currently left these changes out :) 
I personally do not really have the need and capacity to look after that, but I'm happy to see propositions!

**Comment by davwil** [comment]
Energy calculation is integrated into main now :)

**Pull request closed without merging**
